---
- hosts: localhost
  name: "play run in pods"
  tasks:
    - name: Install apache packages
      apt:
        name: apache2
        state: "present"
    - name: Service start
      service:
        name: apache2
        state: started
