apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: dev
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: mynewcon
        image: westuser/newansimg:latest
        ports:
        - containerPort: 80
